[[redirects]]
  from = "/research"
  to   = "/research.html"
  status = 200

[[redirects]]
  from = "/blog"
  to   = "/blog.html"
  status = 200

[[redirects]]
  from = "/post"
  to   = "/post.html"
  status = 200
